#!/usr/bin/env python3

# Example code, configures RGBW scenes for e.g. Aeotec ZW098

import json
import sys
import vera

if len(sys.argv) != 2:
    sys.stderr.write("Usage:\n    test2 <config>\n")
    sys.exit(1)

ve = vera.connect(sys.argv[1])

devices = [
    ve.get_device("Lamp 1"),
    ve.get_device("Lamp 2"),
    ve.get_device("Lamp 3"),
    ve.get_device("Lamp 4")
]

def color(x):
    return vera.Group(0, 
                      [
                          vera.SwitchAction(i, 1)
                          for i in devices
                      ] + [
                          vera.ColorAction(i, x)
                          for i in devices
                      ])

def off():
    return vera.Group(0, [
        vera.SwitchAction(i, "off")
        for i in devices
    ])
    
lighting_scenes = [
    ("Red", color(vera.RGB(80, 0, 0))),
    ("Low Red", color(vera.RGB(30, 0, 0))),
    ("Orange Glow", color(vera.RGB(100, 40, 0))),
    ("Cool Green", color(vera.RGB(0, 90, 20))),
    ("Warm White", color(vera.Warm(120))),
    ("Cool White", color(vera.Daylight(120))),
    ("White Glow", color(vera.Warm(40))),
    ("Off", off())
]

scene_names = set([v[0] for v in lighting_scenes])

scenes = ve.get_scenes()

for sc in scenes:
    if sc.name in scene_names:
        sc.delete()

m = vera.Modes(home=True, away=True, night=True)
room = ve.get_room("Office")

for sc in lighting_scenes:

    name = sc[0]
    actions = sc[1]

    print(name, "...")

    sd = vera.SceneDefinition(name, [], m, [], [actions], room)

    ve.create_scene(sd)


