#!/usr/bin/env python3

# Example code, configures RGBW scenes for e.g. Aeotec ZW098

import json
import sys
import vera

if len(sys.argv) != 2:
    sys.stderr.write("Usage:\n    test2 <config>\n")
    sys.exit(1)

ve = vera.connect(sys.argv[1])

devices = [
    ve.get_device("Lamp 1"),
    ve.get_device("Lamp 2"),
    ve.get_device("Lamp 3"),
    ve.get_device("Lamp 4")
]

on = [
    vera.SwitchAction(i, 1)
    for i in devices
]

scenes = ve.get_scenes()

for sc in scenes:

    if sc.name in ["Red Glow", "Orange Glow", "Warm White", "Cool Green",
                   "Off"]:
        sc.delete()

m = vera.Modes(home=True, away=True, night=True)
room = ve.get_room("Office")

# Red

colour = vera.RGB(80, 0, 0)

actions = vera.Group(0, on + [
    vera.ColorAction(i, colour)
    for i in devices
])

sd = vera.SceneDefinition("Red Glow", [], m, [], [actions], room)

ve.create_scene(sd)

# Orange

colour = vera.RGB(100, 40, 0)

actions = vera.Group(0, on + [
    vera.ColorAction(i, colour)
    for i in devices
])

sd = vera.SceneDefinition("Orange Glow", [], m, [], [actions], room)

ve.create_scene(sd)

# Green

colour = vera.RGB(0, 90, 20)

actions = vera.Group(0, on + [
    vera.ColorAction(i, colour)
    for i in devices
])

sd = vera.SceneDefinition("Cool Green", [], m, [], [actions], room)

ve.create_scene(sd)

# White

colour = vera.Warm(60)

actions = vera.Group(0, on + [
    vera.ColorAction(i, colour)
    for i in devices
])

sd = vera.SceneDefinition("Warm White", [], m, [], [actions], room)

ve.create_scene(sd)

# Off

actions = vera.Group(0, [
    vera.SwitchAction(i, "off")
    for i in devices
])

sd = vera.SceneDefinition("Off", [], m, [], [actions], room)

ve.create_scene(sd)

