#!/usr/bin/env python

import json
import sys
import vera
  
if len(sys.argv) != 3:
    sys.stderr.write("Usage:\n    get_schedule <config> <room>\n")
    sys.exit(1)

config = json.loads(open(sys.argv[1], "r").read())

if config.has_key("local"):
    ve = vera.VeraLocal(config["local"]["address"])
else:
    user = config["remote"]["user"]
    password = config["remote"]["password"]
    device = config["remote"]["device"]
    ve = vera.VeraRemote(user, password, device)

room = ve.get_room(sys.argv[2])

for i in ve.get_scenes():
    if i.room != None:
        if i.room == room:
            print "Deleting scene %s" % i.name

            ve.delete_scene(i)

