#!/usr/bin/env python

import urllib, urllib2, json
import sys
import vera
  
vera = vera.Vera("192.168.0.202")

room = "Heating"
room_id = 0

user_data = vera.get_user_data()

for i in user_data["rooms"]:
    if i["name"] == room:
        room_id = i["id"]

print "Using room id", room_id

status = vera.get_status()

if status.has_key("scenes"):

    for i in status["scenes"]:

        scene = vera.get_scene(i["id"])

        # These happen for deleted scenes?!  Why are they in the list?
        if scene == None: continue
        if not isinstance(scene, dict): continue

        if not scene.has_key("room"): continue
        if int(scene["room"]) != room_id: continue

        if scene.has_key("name"):
            print "Deleting scene", scene["name"]
        else:
            print "Deleting scene id %s" % i["id"]
        
        vera.delete_scene(i["id"])

