#!/usr/bin/env python3

import sys
import vera
import csv
import json

if len(sys.argv) != 2:
    sys.stderr.write("Usage:\n    get_schedule <config>\n")
    sys.exit(1)

config = json.loads(open(sys.argv[1], "r").read())

if "local" in config:
    vera = vera.VeraLocal(config["local"]["address"])
else:
    user = config["remote"]["user"]
    password = config["remote"]["password"]
    device = config["remote"]["device"]
    vera = vera.VeraRemote(user, password, device)

user_data = vera.get_user_data()

print(json.dumps(user_data["scenes"], indent=4))

sys.exit(0)

#print json.dumps(user_data, indent=4)

#print user_data["scenes"]

dev = vera.get_device("Humidity sensor")

print(dev.name, dev.device_json)

data = vera.get_file(dev.device_json)
print(data)

events = data["eventList2"]

for i in events:
    print(i["id"], i["label"]["text"])

sys.exit(0)

print(json.dumps(vera.get_file("D_TemperatureSensor1.json"),indent=4))

#print vera.get_file("S_TemperatureSensor1.xml")


sys.exit(0)

room = vera.get_room_by_id(1)
print(room.id, room.name)

room = vera.get_room("Heating")
print(room.id, room.name)

print()

dev = vera.get_device_by_id(3)
print(dev.id, dev.name)

print()

dev = vera.get_device("Sensor")
print(dev.id, dev.name)
print("%s battery level: %d" % (dev.name, dev.get_battery()))
print("%s temperature sensor: %f" % (dev.name, dev.get_current_temperature()))
print("%s humidity sensor: %d" % (dev.name, dev.get_current_humidity()))

print

dev = vera.get_device("Humidity sensor")
print("%s humidity sensor: %d" % (dev.name, dev.get_current_humidity()))

print

dev = vera.get_device("Bathroom stat", room=room)
print(dev.id, dev.name)
print("%s temperature sensor: %f" % (dev.name, dev.get_current_temperature()))
print("%s is set to: %f" % (dev.name, dev.get_set_point()))
dev.set_set_point(7.0)
print("%s is set to: %f" % (dev.name, dev.get_set_point()))

print 
dev = vera.get_device("Not used")
print(dev.id, dev.name)
dev.set_switch(True)
print("%s switch set to: %s" % (dev.name, dev.get_switch()))
dev.set_switch(False)
print("%s switch set to: %s" % (dev.name, dev.get_switch()))

print()

dev = vera.get_device("Attic")
print(dev.id, dev.name)
print("Attic switch set to:", dev.get_switch())

print()

print("Rooms:")
rooms = vera.get_rooms()
for i in rooms:
    print("  %s: %s" % (i.id, i.name))

print()

print("Devices:")
devices = vera.get_devices()
for i in devices:
    if i.room != None:
        room = i.room.name
    else:
        room = "n/a"
    print("  %s: %s (%s)" % (i.id, i.name, room))

print()

print("Scenes:")
scenes = vera.get_scenes()
for i in scenes:
    print("  %s: %s" % (i.id, i.name))

