#!/usr/bin/env python

import urllib, urllib2, json
import sys
import vera
import csv

if len(sys.argv) != 2:
    sys.stderr.write("Usage:\n    get_schedule <config>\n")
    sys.exit(1)

config = json.loads(open(sys.argv[1], "r").read())

if config.has_key("local"):
    vera = vera.VeraLocal(config["local"]["address"])
else:
    user = config["remote"]["user"]
    password = config["remote"]["password"]
    device = config["remote"]["device"]
    vera = vera.VeraRemote(user, password, device)

room = "Heating"
room_id = 0

user_data = vera.get_user_data()

for i in user_data["rooms"]:
    if i["name"] == room:
        room_id = i["id"]

status = vera.get_status()

output = csv.writer(sys.stdout)

if status.has_key("scenes"):

    for i in status["scenes"]:

        scene = vera.get_scene(i["id"])

        print scene

        # These happen for deleted scenes?!  Why are they in the list?
        if scene == None: continue
        if not isinstance(scene, dict): continue

        if not scene.has_key("room"): continue
        if int(scene["room"]) != room_id: continue

#        continue

        name = scene["name"]
        days = scene["timers"][0]["days_of_week"]
        time = scene["timers"][0]["time"]
        device = scene["groups"][0]["actions"][0]["device"]
        value = scene["groups"][0]["actions"][0]["arguments"][0]["value"]

        output.writerow([name, days, time, device, value])


