#!/usr/bin/env python

import sys
import vera

if len(sys.argv) != 2:
    sys.stderr.write("Usage:\n    get_schedule <config>\n")
    sys.exit(1)

ve = vera.connect(sys.argv[1])

weather = ve.get_weather()

print "Temperature:", weather[0]
print "Outlook:", weather[1]


