#!/usr/bin/env python

import urllib, urllib2, json
import sys
import vera
import csv
import httplib

import logging
import requests

handler = urllib2.HTTPSHandler(debuglevel=65535)
opener = urllib2.build_opener(handler)
urllib2.install_opener(opener)

data = json.loads(open("AUTH", "r").read())
user = data["user"]
password = data["password"]
device = data["device"]
  
vera = vera.VeraRemote(user, password, device)

user_data = vera.get_user_data()
print user_data
sys.exit(0)

sdata = vera.get_sdata()

print sdata

sys.exit(0)

room = "Heating"
room_id = 0

for i in sdata["rooms"]:
    if i["name"] == room:
        room_id = i["id"]

status = vera.get_status()

output = csv.writer(sys.stdout)

if status.has_key("scenes"):

    print "Has scenes"

    print status["scenes"]

    for i in status["scenes"]:

        scene = vera.get_scene(i["id"])

        # These happen for deleted scenes?!  Why are they in the list?
        if scene == None: continue
        if not isinstance(scene, dict): continue

        if not scene.has_key("room"): continue
        if int(scene["room"]) != room_id: continue

        print scene

#        continue

        name = scene["name"]
        days = scene["timers"][0]["days_of_week"]
        time = scene["timers"][0]["time"]
        device = scene["groups"][0]["actions"][0]["device"]
        value = scene["groups"][0]["actions"][0]["arguments"][0]["value"]

        output.writerow([name, days, time, device, value])


