#!/usr/bin/env python3

import vera
import sys

if len(sys.argv) != 4:
    sys.stderr.write("Usage:\n    vera-set-temperature <config> <device> <value>\n")
    sys.exit(1)

ve = vera.connect(sys.argv[1])

device = ve.get_device(sys.argv[2])

device.set_setpoint(float(sys.argv[3]))



