#!/usr/bin/env python3

import sys
import vera
  
if len(sys.argv) != 3:
    sys.stderr.write("Usage:\n    vera-delete-scenes <config> <room>\n")
    sys.exit(1)

ve = vera.connect(sys.argv[1])
room = ve.get_room(sys.argv[2])

for i in ve.get_scenes():
    if i.room != None:
        if i.room == room:
            print("Deleting scene %s" % i.name)

            ve.delete_scene(i)

